### ISSUE TITLE
running the shbaam have some erros??

### ISSUE THREAD

**Issue by Ahmadffrahmand** [c-h-david/shbaam#9]
Respected sir,
i run the cod both in windows and linux i got these errors in ubuntu,

for jupyter i google and i applied all the possibliyi4s 
The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.
and in terminal 

~/.netrc machine urs.earthdata.nasa.gov login YourLogin password YourPassword
/home/user/.netrc: line 1: machine: command not found

i even installed docker for linux but still not solved 
could you please guide,

Regards

**Comment by c-h-david** [comment]
Dear Ahmad,
The `.netrc` file is not meant to be executed. This is a text file where you store your secret credentials to download data from NASA's EarthData portal. Some instructions on how to create an account are in `TUTORIAL.ipynb`. The command to edit this file so that it includes your own credentials is also shown there (the `writefile` step). To be quite frank though, I'm not sure I understand the kernel errors. Our Jupyter implementation of SHBAAM is highly experimental at this point, and I hadn't used it in over a year. But I just ran it with Docker on MacOS and it ran just fine. I've never used Docker on Linux so I can't provide much advice there. It's probably best to try to run it on Linux without Jupyter first just to get acquainted with the software. I hope this helps.
Cedric

**Comment by Ahmadffrahmand** [comment]
Respected Sir.

Thank you very much for your reply.
It's working well after writing my earth data credentials.

But as I sent you an email the problem with downloading CLM data is still
there.

I read the articles about SHBAAM I think it works only with R0L5
parameters. The name and some parameters changed for R0L6 grace data, so it
may give errors for some reason.

But to be honest it will be so help full to use SHBAAM for grace data
processing.

Best Regards

**Comment by c-h-david** [comment]
Thank you for your suggestion to include Release 06 of GRACE data. I'll keep it in mind for next time I do updates on SHBAAM, although I'm not sure at this point when that would be because the project that supported the development of this toolbox is now completed. It also appears that the file `CLM4.SCALE_FACTOR.JPL.MSCNv01CRIv01.nc` is no longer available from PO.DAAC which might explain the issues you ran into. You should be able to use `GRCTellus.JPL.200204_202003.GLO.RL06M.MSCNv02CRI.nc` instead, along with its checksum file `GRCTellus.JPL.200204_202003.GLO.RL06M.MSCNv02CRI.nc.md5`. But please be aware that none of the testing files were produced with this.

**Comment by c-h-david** [comment]
Sorry, I meant `CLM4.SCALE_FACTOR.JPL.MSCNv02CRI.nc` and there is no longer a checksum file.
